# `emacs-lisp' isn't yet supported. If set, it will fallback to `ruby'
# So, use `C' instead.
language: c

git:
  depth: 1

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      env:
        - EMACS=emacs-snapshot
        - ORG_BRANCH=master
        - PPA=ubuntu-elisp/ppa

env:
  global:
    - ORG_REPO=https://code.orgmode.org/bzg/org-mode.git
    - ORG_DIR=org-mode

  matrix:
    - EMACS=emacs-snapshot ORG_BRANCH=maint PPA=ubuntu-elisp/ppa
    - EMACS=emacs-snapshot ORG_BRANCH=master PPA=ubuntu-elisp/ppa

before_install:
  - sudo add-apt-repository -y ppa:$PPA
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

  - git clone --depth=1 --branch $ORG_BRANCH $ORG_REPO && (cd org-mode && echo "autoloads:" > local.mk && make)

script:
  - make test
