# `emacs-lisp' isn't yet supported. If set, it will fallback to `ruby'
# So, use `C' instead.
language: c

env:
  global:
    - ORG_REPO=git://orgmode.org/org-mode.git
    - ORG_DIR=org-mode

  matrix:
    - EMACS=emacs24 ORG_BRANCH=maint
    - EMACS=emacs24 ORG_BRANCH=master
    - EMACS=emacs-snapshot ORG_BRANCH=maint
    - EMACS=emacs-snapshot ORG_BRANCH=master

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

  - git clone --depth=1 --branch $ORG_BRANCH $ORG_REPO && (cd org-mode && echo "autoloads:" > local.mk && make)

script:
  - make test
